name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - run: npm ci
    - run: npm run build --if-present

    - uses: GuillaumeFalourd/setup-rsync@v1.2
      id: rsync
      with:
        ssh_key: ${{ secrets.SITE_SSH }}

    - run: mkdir -p ~/.ssh/ && ssh-keyscan -H zakstroud.com >> ~/.ssh/known_hosts
    - run: rsync -az -e "ssh -i ${{ steps.rsync.outputs.ssh_key_path }}" build/ "${{ secrets.SITE_USER }}@zakstroud.com:${{ secrets.SYNC_DIR }}"

